language: bash
sudo: required
env:
  global:
  - TRAVIS_CI_OPERATOR=1
  - secure: "Soe7CfrBMzbQIIrJi3yFPXWtMtk+gBpdrZrUsNpdNOfqzyiNX72CqNKxHk/BgFKjI3VSpCG1hOjH7ahzq3pUsBE/JoK2sQ0ndO5v4ookFH07V3M1V0jXDWywGpZ/+tmkuHNwljliIJvGO07fOQxgztDxuIfQiJgIN51lW9Hpdq00ADcJC5ouqZRldI1crxu/+CeIaelxk+SvhyuSGuMlG2Chze/Djtys/iPxgdsf2S62j6RNLz78dzTwtACEF7iON8w0pcYlT/hVnIxY29VF6uI92ezPQ+tkrnl6KgqWh7rxtnlUt0lIscTxIGKTgWEQ/QtSa4nNbc02z96qG6c5aWMGo0QGJs8lqz5cH4TGsc/K+tZUz4xvwgVWuY/BzDLHxQBCY4B1PWWHQ1abvBVUX2MdCk3zBa0lbCop/D4iMQZhTLCyyBqFylT6jHRzscxLauYbRfPDqiAWUJJwBYzl5gjteGkdBMpxh/Sd/t6pqWC+1nxw+y8s3E+uldMfVtI1FiopvcpP6qamZMhPys0BauhFX7p+Q7uFq1vHBm4Zhtyd+6ItOY6z6KnuyaewsQEI/tmBegx3yjQCYhYdZ9v2oayT9Wq7P58yfOs2nTDzCutaCgIPhtUmqh7MD1KcUTd/fsAaH5XPXKE3s+1TLvrMS3Rd86TpVJXXShYSj4OXej0="
  - secure: "fZ9wTzMk7bI5iRVJkfksLBuKQ7ISdDoNOqSM+6EJxKwmHkDGOAQG/Z+nu8ZtUpJmG/7VVNoEdBkLiWbA0jgPTAqBs+gDLJzT99khAhCHPHHKcQI7fq10ThdL6Z2VwzHbdoHKvmShBDaDBfDWnFBJDely9zNlMQ+u5bD1itnE/Z/Kd+iXcuVeY0xS8pTagCvBqcUdEO2FwOQQ1jCwVcc5bEoKuc7dlkbaZTaFBmuKIoaQpv9iZcXBroHbfHNqQKfzQ6X1nNbz3D0lA6tULVzAjqaiApI/X7E6Vgc7HCV6AaaZTREdTvfuk6bbF+oGan8SCWPY7ITJjtP9ZmPD59ErjixXUD5pZT5qrRje1waz8+KvKIt5ahdQamz1yXNlQ6WknW1Q2FYnigh5h8g/88PKhjZp1fF7yuc/maqhTCzUfey+06ojVxJxMr4pGHGK3IuIZKwpVk97TPqyDmrdEBnd4mU82YBuDwPbAcWceCnYFRfI1Rf/xsc+r4B/4MaYkeUvkOmEYtABMbXa5Jv3CNH73r7Brt/I8lhnm1bh9cOIuaBTGA9A2kr8BTJ9rF9/qHAZt9JfDSCRXT8YwUQv/Zj2lPXyIJVE7Vs4N9F1tYzMwGm/HJKekiBpl6fN6d/1d8A/qtyr1TnUDhnHf3SvVATsEz+SO/bU/c6TeAa2EvJv0r4="
  - DOCKER_IMAGE=uumpa/hasadna-migdar-internal-search-ui
  - REACT_APP_API_LOCAL_URL=http://localhost:5050/
  - REACT_APP_API_REMOTE_URL=https://migdar-internal-search-backend.odata.org.il/
services:
- docker
install:
- bash .travis.sh install
script:
- bash .travis.sh script
deploy:
  provider: script
  script: bash .travis.sh deploy
  on:
    tags: false
    condition: "$TRAVIS_BRANCH = master"
